// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name ,last_name ,email ,password_hash ,phone_number ,date_of_birth ,is_active)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, TRUE))
RETURNING id, first_name, last_name, email, password_hash, phone_number, date_of_birth, is_active, created_at, updated_at, created_by, updated_by
`

type CreateUserParams struct {
	FirstName    string      `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	Column7      interface{} `json:"column_7"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.PhoneNumber,
		arg.DateOfBirth,
		arg.Column7,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, phone_number, date_of_birth, is_active, created_at, updated_at, created_by, updated_by FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password_hash, phone_number, date_of_birth, is_active, created_at, updated_at, created_by, updated_by FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserIDByCreatedBy = `-- name: GetUserIDByCreatedBy :one
SELECT id FROM users WHERE created_by = $1
`

func (q *Queries) GetUserIDByCreatedBy(ctx context.Context, createdBy pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIDByCreatedBy, createdBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const isEmailTakenByOtherUser = `-- name: IsEmailTakenByOtherUser :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1 AND id <> $2
)
`

type IsEmailTakenByOtherUserParams struct {
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

func (q *Queries) IsEmailTakenByOtherUser(ctx context.Context, arg IsEmailTakenByOtherUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailTakenByOtherUser, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, first_name, last_name, email, password_hash, phone_number, date_of_birth, is_active, created_at, updated_at, created_by, updated_by FROM users
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.PhoneNumber,
			&i.DateOfBirth,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET
  email = COALESCE($1, email),
  first_name = COALESCE($2, first_name),
  last_name = COALESCE($3, last_name),
  phone_number = COALESCE($4, phone_number),
  date_of_birth = COALESCE($5, date_of_birth),
  is_active = COALESCE($6, is_active),
  updated_by = COALESCE($7, updated_by)
WHERE id = $8
RETURNING id, first_name, last_name, email, password_hash, phone_number, date_of_birth, is_active, created_at, updated_at, created_by, updated_by
`

type UpdateUserParams struct {
	Email       pgtype.Text `json:"email"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	IsActive    pgtype.Bool `json:"is_active"`
	UpdatedBy   pgtype.Int4 `json:"updated_by"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.DateOfBirth,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateUserAuditFields = `-- name: UpdateUserAuditFields :exec
UPDATE users
SET created_by = $1,
    updated_by = $2
WHERE id = $3
`

type UpdateUserAuditFieldsParams struct {
	CreatedBy pgtype.Int4 `json:"created_by"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateUserAuditFields(ctx context.Context, arg UpdateUserAuditFieldsParams) error {
	_, err := q.db.Exec(ctx, updateUserAuditFields, arg.CreatedBy, arg.UpdatedBy, arg.ID)
	return err
}
